spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.88.123:9876;
          group: demo
        bindings:
          consumerEvent-in-0:
            subscription: test
            consumer:
              maxConcurrency: 10
              prefetch: 10
          consumerEvent-out-0:
            producer:
              sync: false
      bindings:
        consumerEvent-out-0:
          destination: demo
          content-type: application/json
          group: demo-group

        consumerEvent-in-0:
          destination: demo
          content-type: application/json
          group: demo-group
          consumer:
            concurrency: 3

      function:
        definition: consumerEvent